/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pokemons: Pokemon;
    pokemon_likes: PokemonLike;
    notifications: Notification;
  };
  globals: {};
}
export interface User {
  id: string;
  username?: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  _verified?: boolean;
  _verificationToken?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Pokemon {
  id: string;
  name?: string;
  image?: string;
}
export interface PokemonLike {
  id: string;
  user?: string | User;
  pokemon?: string | Pokemon;
}
export interface Notification {
  id: string;
  to_user?: string | User;
  from_user?: string | User;
  pokemon?: string | Pokemon;
  seen?: boolean;
  updatedAt: string;
  createdAt: string;
}
